#!/bin/sh
#
# @name M130 Rocket  (rocket_M130_v01_CFD68 - HIL via 6DOF_v2_130)
#
# @type Rocket
#
# @maintainer Rocket GNC Team
#
# Physics engine : 6DOF_v2_130  (propulsion + aerodynamics + mass model)
# GNC controller : PX4 rocket_gnc  (guidance + autopilot)
# Protocol       : MAVLink HIL  (HIL_SENSOR / HIL_GPS / HIL_ACTUATOR_CONTROLS)
# Runner         : 6DOF_v2_130/run_px4_hil.py
#
# Parameters tuned for rocket_M130_v01_CFD68:
#   mass_dry=11.11 kg, propellant=1.63 kg, diameter=130 mm
#   Launch: 16.457°N 44.115°E  alt=1200 m MSL
#   Target: 3500 m North  (bearing 0°)
#

. ${R}etc/init.d/rc.rocket_defaults

# HIL mode - all sensor data comes from 6DOF_v2_130 bridge
param set-default SYS_HITL 1

# ---- Rocket GNC parameters (matched to rocket_M130_v01_CFD68 config) ----

# Stage 1: climb to set_alt then transition
param set-default ROCKET_SET_ALT   120.0   # target altitude stage 1 (m)
param set-default ROCKET_T_STG1     15.0   # motor burn time / end of stage 1 (s)
param set-default ROCKET_T_CTRL      0.2   # control start delay after launch (s)

# Guidance - biased proportional navigation
param set-default ROCKET_NPN         2.7   # PN navigation constant  (Npn)
param set-default ROCKET_IMP_ANG   -30.0   # terminal impact angle (deg, neg = dive)
param set-default ROCKET_TAU_PN1    20.0   # bias time constant (s)
param set-default ROCKET_K_YAW    0.008    # yaw guidance gain
param set-default ROCKET_K_VZ      14.0   # velocity error gain

# Acceleration limits
param set-default ROCKET_AYC_LIM    2.0   # yaw accel limit (g)
param set-default ROCKET_APC_LIM    8.0   # pitch accel limit (g)

# Target position in NED (m from launch point)
param set-default ROCKET_XTRGT   3000.0   # North (range_m=3000, bearing=0°)
param set-default ROCKET_YTRGT      0.0   # East
param set-default ROCKET_ZTRGT      0.0   # Down

# Fin deflection limit  (25 deg = 0.436 rad)
param set-default ROCKET_MAX_DEFL  0.436
